name: rep_ftl
version: 0.0.1
dependencies:
  bootstrap: 3.3.6
  ng_bootstrap: ^0.6.6
  angular2: ^3.1.0
  google_maps: ^3.2.1
  googleapis: ^0.41.0
  googleapis_auth: ^0.2.3
dev_dependencies:
  shelf_proxy: ^0.1.0
  dart_to_js_script_rewriter: ^1.0.3
transformers:
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes:
    - package:angular2/common.dart#COMMON_PIPES
    entry_points:
    - web/main.dart
- dart_to_js_script_rewriter
- $dart2js:
    $include: web/main.dart
