name: rep_ftl
version: 0.0.1
dependencies:
  bootstrap: 3.3.6
  ng_bootstrap: ^0.6.6
  angular2: ^3.1.0
dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.3
transformers:
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes:
    - package:angular2/common.dart#COMMON_PIPES
    entry_points:
    - web/main.dart
- dart_to_js_script_rewriter
- $dart2js:
    $include: web/main.dart
